name: CI
on:
  pull_request: {}
  push: {}
permissions: write-all
jobs:
  # ================
  # BUILD AND TEST JOB
  # ================
  test:
    name: Build
    strategy:
      matrix:
        # optionally test/build across multiple platforms/Go-versions
        go-version: ["stable"] # '1.16', '1.17', '1.18,
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Build
        run: go build -v -o /dev/null .
  # ================
  # RELEASE BINARIES (on push "v*" tag)
  # ================
  release_binaries:
    name: Release Binaries
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: goreleaser
        if: success()
        uses: docker://goreleaser/goreleaser:latest
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: release --config .github/goreleaser.yml
